### ISSUE TITLE
Allow :var assignments

### ISSUE THREAD

**Issue by vv3** [TxGVNN/ob-compile#1]
It would be nice if :var assignments worked the same as for `sh` blocks. 

```
#+begin_src compile :var fileName=(buffer-file-name) :var foo="bar"  
  echo "foo: $foo; filename: $fileName"  
#+end_src
```

**Comment by TxGVNN** [comment]
Thanks, this is a great feature that it is missing. I added, please take new version to test and re-open if we need to update.
